class CookieCodec {
  static String domain(String input) {
    final raw = input.trim().toLowerCase().replaceFirst(RegExp(r'^\.+'), '');
    final uri = Uri.tryParse(raw.contains('://') ? raw : 'https://$raw');
    final host = uri?.host ?? '';
    if (uri == null ||
        !['http', 'https'].contains(uri.scheme) ||
        !host.contains('.') ||
        !RegExp(r'^[a-z0-9.-]+$').hasMatch(host) ||
        host.split('.').any((part) =>
            part.isEmpty || part.startsWith('-') || part.endsWith('-'))) {
      throw const FormatException('请输入有效的网站域名或 URL');
    }
    return host;
  }

  static String encode(String raw, String defaultDomain) {
    final host = domain(defaultDomain);
    final content = raw
        .replaceFirst('\uFEFF', '')
        .trimLeft()
        .replaceFirst(RegExp(r'[\r\n]+$'), '');
    final entries = <String>[];
    final netscape = content.contains('\t') ||
        content.startsWith('# Netscape') ||
        content.startsWith('# HTTP Cookie');
    if (netscape) {
      for (final line in content.split(RegExp(r'\r?\n'))) {
        if (line.trim().isEmpty ||
            (line.startsWith('#') && !line.startsWith('#HttpOnly_'))) {
          continue;
        }
        final fields = line.split('\t');
        if (fields.length != 7 ||
            !['TRUE', 'FALSE'].contains(fields[1]) ||
            !['TRUE', 'FALSE'].contains(fields[3]) ||
            !fields[2].startsWith('/') ||
            int.tryParse(fields[4]) == null ||
            int.parse(fields[4]) < 0 ||
            fields[5].isEmpty) {
          throw const FormatException('Cookie 文件格式无效，需要 Netscape 格式的 7 列数据');
        }
        domain(fields[0].replaceFirst('#HttpOnly_', ''));
        entries.add(fields.join('\t'));
      }
    } else {
      for (final segment in content
          .replaceFirst(RegExp(r'^Cookie:\s*', caseSensitive: false), '')
          .split(';')) {
        final pair = segment.trim();
        if (pair.isEmpty) continue;
        final split = pair.indexOf('=');
        if (split <= 0 || pair.contains(RegExp(r'[\r\n\t]'))) {
          throw const FormatException(
              '请输入 name=value 形式的 Cookie 或 Netscape 文件');
        }
        final name = pair.substring(0, split).trim();
        if (name.contains(RegExp(r'\s'))) {
          throw const FormatException('Cookie 名称不能包含空白');
        }
        entries.add(
            '.$host\tTRUE\t/\tFALSE\t0\t$name\t${pair.substring(split + 1).trim()}');
      }
    }
    if (entries.isEmpty) throw const FormatException('未找到有效 Cookie，原配置未更改');
    return '# Netscape HTTP Cookie File\n# Generated by Videoader\n${entries.join('\n')}\n';
  }
}
