name: videoader
description: A desktop FFmpeg toolbox with an optional yt-dlp extension.
publish_to: 'none'

version: 1.1.1+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.0
  file_picker: ^10.3.8
  shared_preferences: ^2.2.0
  path: ^1.9.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.1
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8

# flutter 字段也是顶层配置
flutter:
  uses-material-design: true
  assets:
    - pubspec.yaml
    - LICENSE
    - NOTICE
    - assets/branding/app_icon.png